services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    volumes:
      - ./config.yml:/app/config/config.yml
      - /dev/shm:/dev/shm
    environment:
      - TZ=America/New_York
      - READER_CHROME_PATH=/usr/bin/chromium
      - READER_POOL_SIZE=5
      - READER_BROWSER_TIMEOUT=30
      - READER_MAX_RETRIES=3
      - READER_AI_ENABLED=true
      - READER_AI_ENDPOINT=https://ai.bitop.dev/v1
      - READER_AI_KEY=sk-DqnXzDcKQ3sr3XElix698Q
      - READER_AI_MODEL=vltr-mistral-small
      - READER_LOG_LEVEL=info
      - READER_LOG_JSON=true
      - READER_LOG_CALLER=true
    restart: unless-stopped
    privileged: true
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
