# Server configuration
server:
  # Port to run the server on
  port: 4444
  # Number of browser instances in the pool
  pool_size: 3

# Browser configuration
browser:
  # Optional: Path to Chrome/Chromium executable
  # Leave empty to use system default
  chrome_path: ""

  # Request timeout in seconds
  timeout: 30

  # Maximum memory per browser instance in MB
  max_memory: 128

  # Custom user agent (optional)
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) Chrome/90.0.4430.212"

# AI configuration
ai:
  # Enable/disable AI features
  enabled: true

  # AI API endpoint
  api_endpoint: "https://api.example.com/v1/chat/completions"

  # API key for authentication
  api_key: "your-api-key-here"

  # Model to use for summarization
  model: "gpt-3.5-turbo"

  # Custom prompt for summarization
  prompt: |
    As a summarization assistant, analyze the text and create a clear, concise summary.
    Focus on:
    (1) main ideas and key points
    (2) factual accuracy
    (3) important context
    (4) removing redundancy
    (5) using clear language.
    Keep it brief and accessible while maintaining technical accuracy when present.

# Cache configuration
cache:
  # Maximum age of cached items in seconds
  max_age: 3600

  # Maximum number of items to keep in cache
  max_items: 1000

# Metrics configuration
metrics:
  # Enable/disable Prometheus metrics
  enabled: true

  # Path for metrics endpoint
  path: "/metrics"
