version: '3.8'

services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./screenshots:/app/screenshots
      - ./config.yml:/app/config.yml
    restart: unless-stopped
