version: '3.8'

services:
  reader:
    image: ghcr.io/ncecere/reader:latest
    ports:
      - "4444:4444"
    environment:
      - GOMAXPROCS=4
      - GOGC=100
      - GOMEMLIMIT=128MiB
    volumes:
      - ./screenshots:/home/appuser/screenshots
      - chrome-cache:/tmp/chrome
    tmpfs:
      - /tmp/chrome:exec,size=256m
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4444/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    volumes:
      - .:/app
      - ./screenshots:/home/appuser/screenshots
      - chrome-cache:/tmp/chrome
      - go-cache:/go/pkg/mod
    tmpfs:
      - /tmp/chrome:exec,size=256m
    environment:
      - GOMAXPROCS=4
      - GOGC=100
      - GOMEMLIMIT=128MiB
      - GO_ENV=development
    command: ["air", "-c", ".air.toml"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
  chrome-cache:
  go-cache:
